Created enumarable
alphayowakarindi/enumerable pull request #1
Opened 2022-10-12 14:28 UTC by alphayowakarindi

At this juncture of development we implemented the following:
- Created a class and a method to yield methods from a module.
- Created an enumerable module with several methods to check for true or false status.
- Implemented the methods to yield.

2022-10-12 15:12 UTC, GzimAsani requested changes
### Hello    @alphayowakarindi and @basitali111       :wave:   
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with your first ruby project, it looks great +1:  
 
 ## Required Changes 

- [ ] Please update your readme file, using the Microverse template
- [ ] Check the comment below :arrow_double_down: 






 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-12 15:12 UTC, GzimAsani commented on my_list.rb
> +    @list = list
- [  ] I would suggest you add them this way, it is shorter and looks better and adds them to your list which is an array
```ruby
 def initialize(*args)
        @list = []
        args.each { |arg| @list << arg }
    end
```

2022-10-12 15:12 UTC, GzimAsani commented on my_list.rb
> +end
- [ ] Your class needs to implement `#each` method that yields all members of `@list` in succession. Similar:

```ruby
def each
    return to_enum(:each) unless block_given?

    counter = 0
    while counter < @list.length
      yield(@list[counter])
      counter += 1
    end
    @list
end
```

2022-10-12 15:12 UTC, GzimAsani commented on my_enumerable.rb
> +    end
- [ ] You need to work again on the all and any, they are too specific, you need to take into consideration other cases where they should return false for example:
- list_of_nums.all? {|e| e > 5} should return false, but currently it returns true
- list_of_nums.any? {|e| e == 5} should return false, but currently it returns true

2022-10-13 08:34 UTC, Davidosky007 requested changes
Hi @alphayowakarindi 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
* No linter errors 👍 
* Well written PR description 👍 
* Proper use of Gitflow 👍 

 ## Required Changes ♻️
* As mentioned by the previous reviewer your readme file is not descriptive kindly Add a descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidosky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-13 08:45 UTC, GzimAsani approved these changes
# STATUS: APPROVED :100:         
## There is nothing else to say than it's time to merge... :partying_face: 
Cheers and Happy coding! :clap:  :computer:  :wine_glass: 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


## Optional suggestions
-N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- ### Please add linters, I forgot to mention on the firs review

### Please be reminded to not open a new pull request after you get a review, only use the same one :thought_balloon: 


 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-10-13 08:47 UTC, merged